### ISSUE TITLE
Event for receiving sms

### ISSUE THREAD

**Issue by GiPe66** [yeganemehr/arduino-sim800#1]
Could you please provide an event oriented example for receiving sms ?

**Comment by yeganemehr** [comment]
Hi @GiPe66
It's ready for you: [receive an sms](https://github.com/yeganemehr/arduino-sim800/tree/v0.3.0/examples/receive-sms)

**Comment by GiPe66** [comment]
Thanks. I’ll make a try as soon as I’m back home !

**Comment by GiPe66** [comment]
Works perfectly. Thanks.
